id: AB56A4B9F
title: A Daily Practice of Buddha Akṣobhya
type: translation
pechas:
- I8444C817
- I782F992E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:46:15.417989
  last_modified_at: 2023-01-04 12:46:15.418011
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  I8444C817/4224: B604
  I782F992E/6B2B: B604
